
#include <gtk/gtk.h>
#include "./../include/data.h"
#include <stdlib.h>
#include <string.h>



static void on_activate(GtkApplication *app, gpointer user_data) {
    //intialize the window
    GtkSettings *settings = gtk_settings_get_default();
    g_object_set(settings, "gtk-decoration-layout", "close,maximize,minimize:icon", NULL);
    int WIDTH = 1024;
    int HEIGHT = 720;
    GtkWidget *window = gtk_application_window_new(app);
    gtk_window_set_title(GTK_WINDOW(window), "Management");
    gtk_window_set_default_size(GTK_WINDOW(window), WIDTH, HEIGHT);
    // creating overlay
    GtkWidget *Overlay = gtk_overlay_new();
    gtk_window_set_child(GTK_WINDOW(window), Overlay);
    // Creating The first Page
    GtkWidget *stack = gtk_stack_new();
    gtk_overlay_set_child(GTK_OVERLAY(Overlay), stack);
    //------------------MAIN_MENU----------------------//
    GtkWidget *main_vbox = gtk_box_new(GTK_ORIENTATION_VERTICAL, 0);
    GtkWidget *lists_hbox = gtk_box_new(GTK_ORIENTATION_HORIZONTAL, 20);
    gtk_widget_set_hexpand(main_vbox, TRUE);
    gtk_widget_set_vexpand(main_vbox, TRUE);
    gtk_widget_set_hexpand(lists_hbox, TRUE);
    gtk_widget_set_vexpand(lists_hbox, TRUE);

    // Clients list view
    GtkWidget *clients_vbox = gtk_box_new(GTK_ORIENTATION_VERTICAL, 6);
    gtk_widget_set_hexpand(clients_vbox, TRUE);
    gtk_widget_set_vexpand(clients_vbox, TRUE);
    GtkWidget *clients_label = gtk_label_new("Clients");
    gtk_widget_set_halign(clients_label, GTK_ALIGN_CENTER);
    gtk_box_append(GTK_BOX(clients_vbox), clients_label);
    GtkWidget *client_list_view;
    client_list_view = create_clients_list_view();
    gtk_widget_set_hexpand(client_list_view, TRUE);
    gtk_widget_set_vexpand(client_list_view, TRUE);
    gtk_widget_set_halign(client_list_view, GTK_ALIGN_FILL);
    gtk_widget_set_valign(client_list_view, GTK_ALIGN_FILL);
    gtk_box_append(GTK_BOX(clients_vbox), client_list_view);
    gtk_box_append(GTK_BOX(lists_hbox), clients_vbox);
    // Accounts list view
    GtkWidget *accounts_vbox = gtk_box_new(GTK_ORIENTATION_VERTICAL, 6);
    gtk_widget_set_hexpand(accounts_vbox, TRUE);
    gtk_widget_set_vexpand(accounts_vbox, TRUE);
    GtkWidget *accounts_label = gtk_label_new("Accounts");
    gtk_widget_set_halign(accounts_label, GTK_ALIGN_CENTER);
    gtk_box_append(GTK_BOX(accounts_vbox), accounts_label);
    GtkWidget *comptes_list_view;
    comptes_list_view = create_comptes_list_view();
    gtk_widget_set_hexpand(comptes_list_view, TRUE);
    gtk_widget_set_vexpand(comptes_list_view, TRUE);
    gtk_widget_set_halign(comptes_list_view, GTK_ALIGN_FILL);
    gtk_widget_set_valign(comptes_list_view, GTK_ALIGN_FILL);
    gtk_box_append(GTK_BOX(accounts_vbox), comptes_list_view);
    gtk_box_append(GTK_BOX(lists_hbox), accounts_vbox);
    gtk_box_append(GTK_BOX(main_vbox), lists_hbox);
    // Buttons at the bottom in a horizontal box
    GtkWidget *button_box_main = gtk_box_new(GTK_ORIENTATION_HORIZONTAL, 30);
    gtk_widget_set_halign(button_box_main, GTK_ALIGN_CENTER);
    gtk_widget_set_valign(button_box_main, GTK_ALIGN_END);
    GtkWidget *btn_clients = gtk_button_new_with_label("Client management");
    GtkWidget *btn_comptes = gtk_button_new_with_label("Account management");
    GtkWidget *btn_ops = gtk_button_new_with_label("Operations management");
    GtkWidget *btn_quit = gtk_button_new_with_label("Quit");

    gtk_box_append(GTK_BOX(button_box_main), btn_clients);
    gtk_box_append(GTK_BOX(button_box_main), btn_comptes);
    gtk_box_append(GTK_BOX(button_box_main), btn_ops);
    gtk_box_append(GTK_BOX(button_box_main), btn_quit);
    gtk_widget_set_margin_bottom(btn_clients, 10);
    gtk_widget_set_margin_bottom(btn_comptes, 10);
    gtk_widget_set_margin_bottom(btn_ops, 10);
    gtk_widget_set_margin_bottom(btn_quit, 10);

    gtk_box_append(GTK_BOX(main_vbox), button_box_main);

    // Add the vbox to the stack
    gtk_stack_add_titled(GTK_STACK(stack), main_vbox, "main", "Main Menu");
    gtk_stack_set_visible_child_name(GTK_STACK(stack), "main");

    //-----------------------CLIENT_MENU------------------------------//
    GtkWidget *client_menu = gtk_box_new(GTK_ORIENTATION_HORIZONTAL, 30);
    gtk_widget_set_halign(client_menu, GTK_ALIGN_CENTER);
    gtk_widget_set_valign(client_menu, GTK_ALIGN_END);
    GtkWidget *btn_add = gtk_button_new_with_label("Add client");
    GtkWidget *btn_edit = gtk_button_new_with_label("Edit client");
    GtkWidget *btn_delete = gtk_button_new_with_label("Delete client");
    GtkWidget *btn_search = gtk_button_new_with_label("Search client");
    GtkWidget *btn_back = gtk_button_new_with_label("Back");
    gtk_box_append(GTK_BOX(client_menu), btn_add);
    gtk_box_append(GTK_BOX(client_menu), btn_edit);
    gtk_box_append(GTK_BOX(client_menu), btn_delete);
    gtk_box_append(GTK_BOX(client_menu), btn_search);
    gtk_box_append(GTK_BOX(client_menu), btn_back);
    gtk_widget_set_margin_bottom(btn_add, 10);
    gtk_widget_set_margin_bottom(btn_edit, 10);
    gtk_widget_set_margin_bottom(btn_delete, 10);
    gtk_widget_set_margin_bottom(btn_search, 10);
    gtk_widget_set_margin_bottom(btn_back, 10);
    gtk_stack_add_titled(GTK_STACK(stack), client_menu, "clients", "Clients");
    // adding popup to the overlay
    GtkWidget *POPUP = gtk_box_new(GTK_ORIENTATION_VERTICAL, 0);
    POPUP_GLOBAL = POPUP;
    gtk_widget_set_halign(POPUP, GTK_ALIGN_CENTER);
    gtk_widget_set_valign(POPUP, GTK_ALIGN_CENTER);
    gtk_overlay_add_overlay(GTK_OVERLAY(Overlay), POPUP);
    // scaling the popup horizontaly and verticaly
    gtk_widget_set_hexpand(POPUP, TRUE);
    gtk_widget_set_vexpand(POPUP, TRUE);
    // the visibilty of the popup
    gtk_widget_set_visible(POPUP, FALSE);
    // creating the box container of entrys and buttons (for ajouter clients)
    GtkWidget *entries_container = gtk_box_new(GTK_ORIENTATION_VERTICAL, 0);
    gtk_box_set_spacing(GTK_BOX(entries_container), 10);
    gtk_widget_set_margin_bottom(GTK_WIDGET(entries_container), 10);
    gtk_widget_set_margin_top(GTK_WIDGET(entries_container), 10);
    gtk_widget_set_margin_start(GTK_WIDGET(entries_container), 10);
    gtk_widget_set_margin_end(GTK_WIDGET(entries_container), 10);
    gtk_widget_set_halign(GTK_WIDGET(entries_container), GTK_ALIGN_CENTER);
    gtk_widget_set_valign(GTK_WIDGET(entries_container), GTK_ALIGN_CENTER);
    //creating entries for Adding clients
    GtkWidget *Id_entry = gtk_entry_new();
    gtk_entry_set_placeholder_text(GTK_ENTRY(Id_entry),"Enter ID");
    gtk_box_append(GTK_BOX(entries_container), Id_entry);
    GtkWidget *NOM_CLIENT = gtk_entry_new();
    gtk_entry_set_placeholder_text(GTK_ENTRY(NOM_CLIENT),"Enter surname");
    gtk_box_append(GTK_BOX(entries_container), NOM_CLIENT);
    GtkWidget *PRENOM_CLIENT = gtk_entry_new();
    gtk_entry_set_placeholder_text(GTK_ENTRY(PRENOM_CLIENT),"Enter first name");
    gtk_box_append(GTK_BOX(entries_container), PRENOM_CLIENT);
    GtkWidget *PROFESSION_CLIENT = gtk_entry_new();
    gtk_entry_set_placeholder_text(GTK_ENTRY(PROFESSION_CLIENT),"Enter profession");
    gtk_box_append(GTK_BOX(entries_container), PROFESSION_CLIENT);
    GtkWidget *NUMERO_TELEPHONE = gtk_entry_new();
    gtk_entry_set_placeholder_text(GTK_ENTRY(NUMERO_TELEPHONE),"Enter phone number");
    gtk_box_append(GTK_BOX(entries_container), NUMERO_TELEPHONE);
    gtk_box_append(GTK_BOX(POPUP), entries_container);
    gtk_widget_set_size_request(Id_entry, 500, -1);       
    // adding OK/Cancel button
    GtkWidget *button_box_add = gtk_box_new(GTK_ORIENTATION_HORIZONTAL, 450);
    gtk_widget_set_hexpand(button_box_add, TRUE);
    GtkWidget *OK_BUTTON = gtk_button_new_with_label("OK");
    GtkWidget *CANCEL_BUTTON = gtk_button_new_with_label("Cancel");
    gtk_box_append(GTK_BOX(button_box_add), OK_BUTTON);
    gtk_box_append(GTK_BOX(button_box_add), CANCEL_BUTTON);
    gtk_box_append(GTK_BOX(entries_container), button_box_add);
    gtk_widget_set_halign(OK_BUTTON, GTK_ALIGN_START);
    gtk_widget_set_halign(CANCEL_BUTTON, GTK_ALIGN_END);
    GtkWidget *info_label = gtk_label_new("");
    gtk_box_append(GTK_BOX(entries_container), info_label);
    GtkWidget *POPUP_2 = gtk_box_new(GTK_ORIENTATION_VERTICAL, 0);
    POPUP_2_GLOBAL = POPUP_2;
    gtk_widget_set_halign(POPUP_2, GTK_ALIGN_CENTER);
    gtk_widget_set_valign(POPUP_2, GTK_ALIGN_CENTER);
    gtk_overlay_add_overlay(GTK_OVERLAY(Overlay), POPUP_2);
    gtk_widget_set_visible(POPUP_2, FALSE);
    // creating the box container of entries and buttons (for modfier clients)
    GtkWidget *entries_container_2 = gtk_box_new(GTK_ORIENTATION_VERTICAL, 0);
    gtk_box_set_spacing(GTK_BOX(entries_container_2), 10);
    gtk_widget_set_margin_bottom(GTK_WIDGET(entries_container_2), 10);
    gtk_widget_set_margin_top(GTK_WIDGET(entries_container_2), 10);
    gtk_widget_set_margin_start(GTK_WIDGET(entries_container_2), 10);
    gtk_widget_set_margin_end(GTK_WIDGET(entries_container_2), 10);
    gtk_widget_set_halign(GTK_WIDGET(entries_container_2), GTK_ALIGN_CENTER);
    gtk_widget_set_valign(GTK_WIDGET(entries_container_2), GTK_ALIGN_CENTER);
    //creating entries for Modif clients
    GtkWidget *Id_entry_2 = gtk_entry_new();
    gtk_entry_set_placeholder_text(GTK_ENTRY(Id_entry_2),"Enter ID");
    gtk_box_append(GTK_BOX(entries_container_2), Id_entry_2);
    GtkWidget *NOM_CLIENT_2 = gtk_entry_new();
    gtk_entry_set_placeholder_text(GTK_ENTRY(NOM_CLIENT_2),"Edit surname");
    gtk_box_append(GTK_BOX(entries_container_2), NOM_CLIENT_2);
    GtkWidget *PRENOM_CLIENT_2 = gtk_entry_new();
    gtk_entry_set_placeholder_text(GTK_ENTRY(PRENOM_CLIENT_2),"Edit first name");
    gtk_box_append(GTK_BOX(entries_container_2), PRENOM_CLIENT_2);
    GtkWidget *NUMERO_TELEPHONE_2 = gtk_entry_new();
    gtk_entry_set_placeholder_text(GTK_ENTRY(NUMERO_TELEPHONE_2),"Edit phone number");
    gtk_box_append(GTK_BOX(entries_container_2), NUMERO_TELEPHONE_2);
    GtkWidget *PROFESSION_CLIENT_2 = gtk_entry_new();
    gtk_entry_set_placeholder_text(GTK_ENTRY(PROFESSION_CLIENT_2),"Edit profession");
    gtk_box_append(GTK_BOX(entries_container_2), PROFESSION_CLIENT_2);
    GtkWidget *info_label_2 = gtk_label_new("");
    gtk_box_append(GTK_BOX(entries_container_2), info_label_2);
    gtk_box_append(GTK_BOX(POPUP_2), entries_container_2);
    gtk_widget_set_size_request(Id_entry_2, 500, -1);
    // adding OK/Cancel button (modfier_client)
    GtkWidget *button_box_edit = gtk_box_new(GTK_ORIENTATION_HORIZONTAL, 450);
    gtk_widget_set_hexpand(button_box_edit, TRUE);
    GtkWidget *OK_BUTTON_2 = gtk_button_new_with_label("OK");
    GtkWidget *CANCEL_BUTTON_2 = gtk_button_new_with_label("Cancel");
    gtk_box_append(GTK_BOX(button_box_edit), OK_BUTTON_2);
    gtk_box_append(GTK_BOX(button_box_edit), CANCEL_BUTTON_2);
    gtk_box_append(GTK_BOX(entries_container_2), button_box_edit);
    gtk_widget_set_halign(OK_BUTTON_2, GTK_ALIGN_START);
    gtk_widget_set_halign(CANCEL_BUTTON_2, GTK_ALIGN_END);
    //Supprimer Client Popup
    GtkWidget *POPUP_3 = gtk_box_new(GTK_ORIENTATION_VERTICAL, 0);
    POPUP_3_GLOBAL = POPUP_3;
    gtk_widget_set_halign(POPUP_3, GTK_ALIGN_CENTER);
    gtk_widget_set_valign(POPUP_3, GTK_ALIGN_CENTER);
    gtk_overlay_add_overlay(GTK_OVERLAY(Overlay), POPUP_3);
    gtk_widget_set_hexpand(POPUP_3, TRUE);
    gtk_widget_set_vexpand(POPUP_3, TRUE);
    gtk_widget_set_visible(POPUP_3, FALSE);
    GtkWidget *entries_container_3 = gtk_box_new(GTK_ORIENTATION_VERTICAL, 0);
    gtk_box_set_spacing(GTK_BOX(entries_container_3), 10);
    gtk_widget_set_margin_bottom(GTK_WIDGET(entries_container_3), 10);
    gtk_widget_set_margin_top(GTK_WIDGET(entries_container_3), 10);
    gtk_widget_set_margin_start(GTK_WIDGET(entries_container_3), 10);
    gtk_widget_set_margin_end(GTK_WIDGET(entries_container_3), 10);
    gtk_widget_set_halign(GTK_WIDGET(entries_container_3), GTK_ALIGN_CENTER);
    gtk_widget_set_valign(GTK_WIDGET(entries_container_3), GTK_ALIGN_CENTER);
    GtkWidget *info_label_3 = gtk_label_new("");
    gtk_box_append(GTK_BOX(entries_container_3), info_label_3);
    GtkWidget *Id_entry_3 = gtk_entry_new();
    gtk_entry_set_placeholder_text(GTK_ENTRY(Id_entry_3),"Enter ID to delete");
    gtk_box_append(GTK_BOX(entries_container_3), Id_entry_3);
    GtkWidget *button_box_delete = gtk_box_new(GTK_ORIENTATION_HORIZONTAL, 450);
    gtk_widget_set_hexpand(button_box_delete, TRUE);
    GtkWidget *OK_BUTTON_3 = gtk_button_new_with_label("OK");
    GtkWidget *CANCEL_BUTTON_3 = gtk_button_new_with_label("Cancel");
    gtk_box_append(GTK_BOX(button_box_delete), OK_BUTTON_3);
    gtk_box_append(GTK_BOX(button_box_delete), CANCEL_BUTTON_3);
    gtk_box_append(GTK_BOX(entries_container_3), button_box_delete);
    gtk_widget_set_halign(OK_BUTTON_3, GTK_ALIGN_START);
    gtk_widget_set_halign(CANCEL_BUTTON_3, GTK_ALIGN_END);
    gtk_box_append(GTK_BOX(POPUP_3), entries_container_3);
    // Search Client Popup (name)
    GtkWidget *POPUP_SEARCH_CLIENT_CHOICE = gtk_box_new(GTK_ORIENTATION_VERTICAL, 0);
    POPUP_SEARCH_CLIENT_CHOICE_GLOBAL = POPUP_SEARCH_CLIENT_CHOICE;
    gtk_widget_set_halign(POPUP_SEARCH_CLIENT_CHOICE, GTK_ALIGN_CENTER);
    gtk_widget_set_valign(POPUP_SEARCH_CLIENT_CHOICE, GTK_ALIGN_CENTER);
    gtk_overlay_add_overlay(GTK_OVERLAY(Overlay), POPUP_SEARCH_CLIENT_CHOICE);
    gtk_widget_set_hexpand(POPUP_SEARCH_CLIENT_CHOICE, TRUE);
    gtk_widget_set_vexpand(POPUP_SEARCH_CLIENT_CHOICE, TRUE);
    gtk_widget_set_visible(POPUP_SEARCH_CLIENT_CHOICE, FALSE);
    GtkWidget *search_choice_box = gtk_box_new(GTK_ORIENTATION_VERTICAL, 10);
    gtk_widget_set_margin_bottom(search_choice_box, 10);
    gtk_widget_set_margin_top(search_choice_box, 10);
    gtk_widget_set_margin_start(search_choice_box, 10);
    gtk_widget_set_margin_end(search_choice_box, 10);
    gtk_widget_set_halign(search_choice_box, GTK_ALIGN_CENTER);
    gtk_widget_set_valign(search_choice_box, GTK_ALIGN_CENTER);
    GtkWidget *btn_search_by_name = gtk_button_new_with_label("Search by name & surname");
    GtkWidget *btn_search_by_id = gtk_button_new_with_label("Search by ID");
    GtkWidget *btn_search_choice_cancel = gtk_button_new_with_label("Cancel");
    gtk_box_append(GTK_BOX(search_choice_box), btn_search_by_name);
    gtk_box_append(GTK_BOX(search_choice_box), btn_search_by_id);
    gtk_box_append(GTK_BOX(search_choice_box), btn_search_choice_cancel);
    gtk_box_append(GTK_BOX(POPUP_SEARCH_CLIENT_CHOICE), search_choice_box);
    // Search Client Popup ( id)
    GtkWidget *POPUP_SEARCH_CLIENT = gtk_box_new(GTK_ORIENTATION_VERTICAL, 0);
    POPUP_SEARCH_CLIENT_GLOBAL = POPUP_SEARCH_CLIENT;
    gtk_widget_set_halign(POPUP_SEARCH_CLIENT, GTK_ALIGN_CENTER);
    gtk_widget_set_valign(POPUP_SEARCH_CLIENT, GTK_ALIGN_CENTER);
    gtk_overlay_add_overlay(GTK_OVERLAY(Overlay), POPUP_SEARCH_CLIENT);
    gtk_widget_set_hexpand(POPUP_SEARCH_CLIENT, TRUE);
    gtk_widget_set_vexpand(POPUP_SEARCH_CLIENT, TRUE);
    gtk_widget_set_visible(POPUP_SEARCH_CLIENT, FALSE);
    GtkWidget *entries_container_search_id = gtk_box_new(GTK_ORIENTATION_VERTICAL, 0);
    gtk_box_set_spacing(GTK_BOX(entries_container_search_id), 10);
    gtk_widget_set_margin_bottom(GTK_WIDGET(entries_container_search_id), 10);
    gtk_widget_set_margin_top(GTK_WIDGET(entries_container_search_id), 10);
    gtk_widget_set_margin_start(GTK_WIDGET(entries_container_search_id), 10);
    gtk_widget_set_margin_end(GTK_WIDGET(entries_container_search_id), 10);
    gtk_widget_set_halign(GTK_WIDGET(entries_container_search_id), GTK_ALIGN_CENTER);
    gtk_widget_set_valign(GTK_WIDGET(entries_container_search_id), GTK_ALIGN_CENTER);
    GtkWidget *Id_search_client = gtk_entry_new();
    gtk_entry_set_placeholder_text(GTK_ENTRY(Id_search_client),"Enter client ID");
    gtk_box_append(GTK_BOX(entries_container_search_id), Id_search_client);
    gtk_widget_set_size_request(Id_search_client, 500, -1);
    GtkWidget *button_box_search_id = gtk_box_new(GTK_ORIENTATION_HORIZONTAL, 450);
    gtk_widget_set_hexpand(button_box_search_id, TRUE);
    GtkWidget *OK_BUTTON_SEARCH_ID = gtk_button_new_with_label("OK");
    GtkWidget *CANCEL_BUTTON_SEARCH_ID = gtk_button_new_with_label("Cancel");
    gtk_box_append(GTK_BOX(button_box_search_id), OK_BUTTON_SEARCH_ID);
    gtk_box_append(GTK_BOX(button_box_search_id), CANCEL_BUTTON_SEARCH_ID);
    gtk_box_append(GTK_BOX(entries_container_search_id), button_box_search_id);
    gtk_widget_set_halign(OK_BUTTON_SEARCH_ID, GTK_ALIGN_START);
    gtk_widget_set_halign(CANCEL_BUTTON_SEARCH_ID, GTK_ALIGN_END);
    gtk_box_append(GTK_BOX(POPUP_SEARCH_CLIENT), entries_container_search_id);

    GtkWidget *entries_container_search_name = gtk_box_new(GTK_ORIENTATION_VERTICAL, 0);
    gtk_box_set_spacing(GTK_BOX(entries_container_search_name), 10);
    gtk_widget_set_margin_bottom(GTK_WIDGET(entries_container_search_name), 10);
    gtk_widget_set_margin_top(GTK_WIDGET(entries_container_search_name), 10);
    gtk_widget_set_margin_start(GTK_WIDGET(entries_container_search_name), 10);
    gtk_widget_set_margin_end(GTK_WIDGET(entries_container_search_name), 10);
    gtk_widget_set_halign(GTK_WIDGET(entries_container_search_name), GTK_ALIGN_CENTER);
    gtk_widget_set_valign(GTK_WIDGET(entries_container_search_name), GTK_ALIGN_CENTER);
    GtkWidget *Nom_search_client = gtk_entry_new();
    gtk_entry_set_placeholder_text(GTK_ENTRY(Nom_search_client),"Enter surname");
    gtk_box_append(GTK_BOX(entries_container_search_name), Nom_search_client);
    GtkWidget *Prenom_search_client = gtk_entry_new();
    gtk_entry_set_placeholder_text(GTK_ENTRY(Prenom_search_client),"Enter first name");
    gtk_box_append(GTK_BOX(entries_container_search_name), Prenom_search_client);
    GtkWidget *button_box_search_name = gtk_box_new(GTK_ORIENTATION_HORIZONTAL, 450);
    gtk_widget_set_hexpand(button_box_search_name, TRUE);
    GtkWidget *OK_BUTTON_SEARCH_NAME = gtk_button_new_with_label("OK");
    GtkWidget *CANCEL_BUTTON_SEARCH_NAME = gtk_button_new_with_label("Cancel");
    gtk_box_append(GTK_BOX(button_box_search_name), OK_BUTTON_SEARCH_NAME);
    gtk_box_append(GTK_BOX(button_box_search_name), CANCEL_BUTTON_SEARCH_NAME);
    gtk_box_append(GTK_BOX(entries_container_search_name), button_box_search_name);
    gtk_widget_set_halign(OK_BUTTON_SEARCH_NAME, GTK_ALIGN_START);
    gtk_widget_set_halign(CANCEL_BUTTON_SEARCH_NAME, GTK_ALIGN_END);
    gtk_box_append(GTK_BOX(POPUP_SEARCH_CLIENT), entries_container_search_name);

    GtkWidget *info_label_search = gtk_label_new("");
    gtk_box_append(GTK_BOX(POPUP_SEARCH_CLIENT), info_label_search);
    GtkWidget *search_client_list_view = create_search_client_list_view();
    gtk_box_append(GTK_BOX(POPUP_SEARCH_CLIENT), search_client_list_view);
    gtk_widget_set_hexpand(search_client_list_view, TRUE);
    gtk_widget_set_vexpand(search_client_list_view, TRUE);
    gtk_widget_set_visible(search_client_list_view, FALSE);
    gtk_widget_set_visible(entries_container_search_name, FALSE);
    gtk_widget_set_visible(button_box_search_name, FALSE);

    //-----------------------COMPTE_MENU----------------------------//
  
    GtkWidget *compte_menu = gtk_box_new(GTK_ORIENTATION_HORIZONTAL, 30);
    gtk_widget_set_halign(compte_menu, GTK_ALIGN_CENTER);
    gtk_widget_set_valign(compte_menu, GTK_ALIGN_END);
    GtkWidget *btn_nouveau_compte = gtk_button_new_with_label("New account");
    GtkWidget *btn_consultation = gtk_button_new_with_label("Consultation");
    GtkWidget *btn_fermeture_compte = gtk_button_new_with_label("Close account");
    GtkWidget *btn_back_compte = gtk_button_new_with_label("Back");
    gtk_box_append(GTK_BOX(compte_menu), btn_nouveau_compte);
    gtk_box_append(GTK_BOX(compte_menu), btn_consultation);
    gtk_box_append(GTK_BOX(compte_menu), btn_fermeture_compte);
    gtk_box_append(GTK_BOX(compte_menu), btn_back_compte);
    gtk_widget_set_margin_bottom(btn_nouveau_compte, 10);
    gtk_widget_set_margin_bottom(btn_consultation, 10);
    gtk_widget_set_margin_bottom(btn_fermeture_compte, 10);
    gtk_widget_set_margin_bottom(btn_back_compte, 10);
    gtk_stack_add_titled(GTK_STACK(stack), compte_menu, "Compte_Menu", "Accounts");
    GtkWidget *POPUP_COMPTE = gtk_box_new(GTK_ORIENTATION_VERTICAL, 0);
    POPUP_COMPTE_GLOBAL = POPUP_COMPTE;
    gtk_widget_set_halign(POPUP_COMPTE, GTK_ALIGN_CENTER);
    gtk_widget_set_valign(POPUP_COMPTE, GTK_ALIGN_CENTER);
    gtk_overlay_add_overlay(GTK_OVERLAY(Overlay), POPUP_COMPTE);
    gtk_widget_set_hexpand(POPUP_COMPTE, TRUE);
    gtk_widget_set_vexpand(POPUP_COMPTE, TRUE);
    gtk_widget_set_visible(POPUP_COMPTE, FALSE);
    GtkWidget *entries_container_compte = gtk_box_new(GTK_ORIENTATION_VERTICAL, 0);
    gtk_box_set_spacing(GTK_BOX(entries_container_compte), 10);
    gtk_widget_set_margin_bottom(GTK_WIDGET(entries_container_compte), 10);
    gtk_widget_set_margin_top(GTK_WIDGET(entries_container_compte), 10);
    gtk_widget_set_margin_start(GTK_WIDGET(entries_container_compte), 10);
    gtk_widget_set_margin_end(GTK_WIDGET(entries_container_compte), 10);
    gtk_widget_set_halign(GTK_WIDGET(entries_container_compte), GTK_ALIGN_CENTER);
    gtk_widget_set_valign(GTK_WIDGET(entries_container_compte), GTK_ALIGN_CENTER);
    GtkWidget *Id_client_entry = gtk_entry_new();
    gtk_entry_set_placeholder_text(GTK_ENTRY(Id_client_entry),"Enter client ID");
    gtk_box_append(GTK_BOX(entries_container_compte), Id_client_entry);
    GtkWidget *Id_compte_entry = gtk_entry_new();
    gtk_entry_set_placeholder_text(GTK_ENTRY(Id_compte_entry),"Enter account ID");
    gtk_box_append(GTK_BOX(entries_container_compte), Id_compte_entry);
    GtkWidget *Nom_Compte_entry = gtk_entry_new();
    gtk_entry_set_placeholder_text(GTK_ENTRY(Nom_Compte_entry),"Enter surname");
    gtk_box_append(GTK_BOX(entries_container_compte), Nom_Compte_entry);
    GtkWidget *Prenom_Compte_entry = gtk_entry_new();
    gtk_entry_set_placeholder_text(GTK_ENTRY(Prenom_Compte_entry),"Enter first name");
    gtk_box_append(GTK_BOX(entries_container_compte), Prenom_Compte_entry);
    GtkWidget *Solde_Compte_entry = gtk_entry_new();
    gtk_entry_set_placeholder_text(GTK_ENTRY(Solde_Compte_entry),"Enter opening balance");
    gtk_box_append(GTK_BOX(entries_container_compte), Solde_Compte_entry);
    GtkWidget *Date_Compte_entry = gtk_entry_new();
    gtk_entry_set_placeholder_text(GTK_ENTRY(Date_Compte_entry),"Enter opening date");
    gtk_box_append(GTK_BOX(entries_container_compte), Date_Compte_entry);
    GtkWidget *info_Compte_label = gtk_label_new("");
    gtk_box_append(GTK_BOX(entries_container_compte), info_Compte_label);
    gtk_box_append(GTK_BOX(POPUP_COMPTE), entries_container_compte);
    gtk_widget_set_size_request(Id_client_entry, 500, -1);
    GtkWidget *button_box_compte = gtk_box_new(GTK_ORIENTATION_HORIZONTAL, 450);
    gtk_widget_set_hexpand(button_box_compte, TRUE);
    GtkWidget *OK_BUTTON_COMPTE = gtk_button_new_with_label("OK");
    GtkWidget *CANCEL_BUTTON_COMPTE = gtk_button_new_with_label("Cancel");
    gtk_box_append(GTK_BOX(button_box_compte), OK_BUTTON_COMPTE);
    gtk_box_append(GTK_BOX(button_box_compte), CANCEL_BUTTON_COMPTE);
    gtk_box_append(GTK_BOX(entries_container_compte), button_box_compte);
    gtk_widget_set_halign(OK_BUTTON_COMPTE, GTK_ALIGN_START);
    gtk_widget_set_halign(CANCEL_BUTTON_COMPTE, GTK_ALIGN_END);
    GtkWidget *POPUP_FERMETURE_COMPTE = gtk_box_new(GTK_ORIENTATION_VERTICAL, 0);
    POPUP_FERMETURE_COMPTE_GLOBAL = POPUP_FERMETURE_COMPTE;
    gtk_widget_set_halign(POPUP_FERMETURE_COMPTE, GTK_ALIGN_CENTER);
    gtk_widget_set_valign(POPUP_FERMETURE_COMPTE, GTK_ALIGN_CENTER);
    gtk_overlay_add_overlay(GTK_OVERLAY(Overlay), POPUP_FERMETURE_COMPTE);
    gtk_widget_set_hexpand(POPUP_FERMETURE_COMPTE, TRUE);
    gtk_widget_set_vexpand(POPUP_FERMETURE_COMPTE, TRUE);
    gtk_widget_set_visible(POPUP_FERMETURE_COMPTE, FALSE);
    GtkWidget *entries_container_fermeture = gtk_box_new(GTK_ORIENTATION_VERTICAL, 0);
    gtk_box_set_spacing(GTK_BOX(entries_container_fermeture), 10);
    gtk_widget_set_margin_bottom(GTK_WIDGET(entries_container_fermeture), 10);
    gtk_widget_set_margin_top(GTK_WIDGET(entries_container_fermeture), 10);
    gtk_widget_set_margin_start(GTK_WIDGET(entries_container_fermeture), 10);
    gtk_widget_set_margin_end(GTK_WIDGET(entries_container_fermeture), 10);
    gtk_widget_set_halign(GTK_WIDGET(entries_container_fermeture), GTK_ALIGN_CENTER);
    gtk_widget_set_valign(GTK_WIDGET(entries_container_fermeture), GTK_ALIGN_CENTER);
    GtkWidget *Id_fermeture_entry = gtk_entry_new();
    gtk_entry_set_placeholder_text(GTK_ENTRY(Id_fermeture_entry),"Enter account ID to close");
    gtk_box_append(GTK_BOX(entries_container_fermeture), Id_fermeture_entry);
    GtkWidget *Id_fermeture_client_entry = gtk_entry_new();
    gtk_entry_set_placeholder_text(GTK_ENTRY(Id_fermeture_client_entry),"Enter client ID");
    gtk_box_append(GTK_BOX(entries_container_fermeture), Id_fermeture_client_entry);
    GtkWidget *info_label_fermeture = gtk_label_new("");
    gtk_box_append(GTK_BOX(entries_container_fermeture), info_label_fermeture);
    gtk_box_append(GTK_BOX(POPUP_FERMETURE_COMPTE), entries_container_fermeture);
    gtk_widget_set_size_request(Id_fermeture_entry, 500, -1);
    GtkWidget *button_box_fermeture = gtk_box_new(GTK_ORIENTATION_HORIZONTAL, 450);
    gtk_widget_set_hexpand(button_box_fermeture, TRUE);
    GtkWidget *OK_BUTTON_FERMETURE = gtk_button_new_with_label("OK");
    GtkWidget *CANCEL_BUTTON_FERMETURE = gtk_button_new_with_label("Cancel");
    gtk_box_append(GTK_BOX(button_box_fermeture), OK_BUTTON_FERMETURE);
    gtk_box_append(GTK_BOX(button_box_fermeture), CANCEL_BUTTON_FERMETURE);
    gtk_box_append(GTK_BOX(entries_container_fermeture), button_box_fermeture);
    gtk_widget_set_halign(OK_BUTTON_FERMETURE, GTK_ALIGN_START);
    gtk_widget_set_halign(CANCEL_BUTTON_FERMETURE, GTK_ALIGN_END);

    //-----------------------OPERATION_MENU----------------------------//
    GtkWidget *operation_menu = gtk_box_new(GTK_ORIENTATION_HORIZONTAL, 30);
    gtk_widget_set_halign(operation_menu, GTK_ALIGN_CENTER);
    gtk_widget_set_valign(operation_menu, GTK_ALIGN_END);
    GtkWidget *btn_retrait = gtk_button_new_with_label("Withdrawal");
    GtkWidget *btn_virement = gtk_button_new_with_label("Transfer");
    GtkWidget *btn_back_operation = gtk_button_new_with_label("Back");
    gtk_box_append(GTK_BOX(operation_menu), btn_retrait);
    gtk_box_append(GTK_BOX(operation_menu), btn_virement);
    gtk_box_append(GTK_BOX(operation_menu), btn_back_operation);
    gtk_widget_set_margin_bottom(btn_retrait, 10);
    gtk_widget_set_margin_bottom(btn_virement, 10);
    gtk_widget_set_margin_bottom(btn_back_operation, 10);
    gtk_stack_add_titled(GTK_STACK(stack), operation_menu, "Operation_Menu", "Operations");
    GtkWidget *POPUP_OPERATION_RETRAIT = gtk_box_new(GTK_ORIENTATION_VERTICAL, 0);
    POPUP_OPERATION_RETRAIT_GLOBAL = POPUP_OPERATION_RETRAIT;
    gtk_widget_set_halign(POPUP_OPERATION_RETRAIT, GTK_ALIGN_CENTER);
    gtk_widget_set_valign(POPUP_OPERATION_RETRAIT, GTK_ALIGN_CENTER);
    gtk_overlay_add_overlay(GTK_OVERLAY(Overlay), POPUP_OPERATION_RETRAIT);
    gtk_widget_set_hexpand(POPUP_OPERATION_RETRAIT, TRUE);
    gtk_widget_set_vexpand(POPUP_OPERATION_RETRAIT, TRUE);
    gtk_widget_set_visible(POPUP_OPERATION_RETRAIT, FALSE);
    GtkWidget *entries_container_operation_retrait = gtk_box_new(GTK_ORIENTATION_VERTICAL, 0);
    gtk_box_set_spacing(GTK_BOX(entries_container_operation_retrait), 10);
    gtk_widget_set_margin_bottom(GTK_WIDGET(entries_container_operation_retrait), 10);
    gtk_widget_set_margin_top(GTK_WIDGET(entries_container_operation_retrait), 10);
    gtk_widget_set_margin_start(GTK_WIDGET(entries_container_operation_retrait), 10);
    gtk_widget_set_margin_end(GTK_WIDGET(entries_container_operation_retrait), 10);
    gtk_widget_set_halign(GTK_WIDGET(entries_container_operation_retrait), GTK_ALIGN_CENTER);
    gtk_widget_set_valign(GTK_WIDGET(entries_container_operation_retrait), GTK_ALIGN_CENTER);
    GtkWidget *Id_client_entry_retrait = gtk_entry_new();
    gtk_entry_set_placeholder_text(GTK_ENTRY(Id_client_entry_retrait),"Enter client ID");
    gtk_box_append(GTK_BOX(entries_container_operation_retrait), Id_client_entry_retrait);
    GtkWidget *Id_compte_entry_retrait = gtk_entry_new();
    gtk_entry_set_placeholder_text(GTK_ENTRY(Id_compte_entry_retrait),"Enter account ID");
    gtk_box_append(GTK_BOX(entries_container_operation_retrait), Id_compte_entry_retrait);
    GtkWidget *Withdrawal_entry = gtk_entry_new();
    gtk_entry_set_placeholder_text(GTK_ENTRY(Withdrawal_entry),"Amount to withdraw");
    gtk_box_append(GTK_BOX(entries_container_operation_retrait), Withdrawal_entry);
    GtkWidget *info_Withdrawal_label = gtk_label_new("");
    gtk_box_append(GTK_BOX(entries_container_operation_retrait), info_Withdrawal_label);
    gtk_box_append(GTK_BOX(POPUP_OPERATION_RETRAIT), entries_container_operation_retrait);
    gtk_widget_set_size_request(Id_client_entry_retrait, 500, -1);
    // OK/Cancel buttons
    GtkWidget *button_box_operation_retrait = gtk_box_new(GTK_ORIENTATION_HORIZONTAL, 450);
    gtk_widget_set_hexpand(button_box_operation_retrait, TRUE);
    GtkWidget *OK_BUTTON_OPERATION_RETRAIT = gtk_button_new_with_label("OK");
    GtkWidget *CANCEL_BUTTON_OPERATION_RETRAIT = gtk_button_new_with_label("Cancel");
    gtk_box_append(GTK_BOX(button_box_operation_retrait), OK_BUTTON_OPERATION_RETRAIT);
    gtk_box_append(GTK_BOX(button_box_operation_retrait), CANCEL_BUTTON_OPERATION_RETRAIT);
    gtk_box_append(GTK_BOX(entries_container_operation_retrait), button_box_operation_retrait);
    gtk_widget_set_halign(OK_BUTTON_OPERATION_RETRAIT, GTK_ALIGN_START);
    gtk_widget_set_halign(CANCEL_BUTTON_OPERATION_RETRAIT, GTK_ALIGN_END);
    GtkWidget *POPUP_OPERATION_VIREMENT = gtk_box_new(GTK_ORIENTATION_VERTICAL, 0);
    POPUP_OPERATION_VIREMENT_GLOBAL = POPUP_OPERATION_VIREMENT;
    gtk_widget_set_halign(POPUP_OPERATION_VIREMENT, GTK_ALIGN_CENTER);
    gtk_widget_set_valign(POPUP_OPERATION_VIREMENT, GTK_ALIGN_CENTER);
    gtk_overlay_add_overlay(GTK_OVERLAY(Overlay), POPUP_OPERATION_VIREMENT);
    gtk_widget_set_hexpand(POPUP_OPERATION_VIREMENT, TRUE);
    gtk_widget_set_vexpand(POPUP_OPERATION_VIREMENT, TRUE);
    gtk_widget_set_visible(POPUP_OPERATION_VIREMENT, FALSE);
    GtkWidget *entries_operation_virement = gtk_box_new(GTK_ORIENTATION_VERTICAL, 0);
    gtk_box_set_spacing(GTK_BOX(entries_operation_virement), 10);
    gtk_widget_set_margin_bottom(GTK_WIDGET(entries_operation_virement), 10);
    gtk_widget_set_margin_top(GTK_WIDGET(entries_operation_virement), 10);
    gtk_widget_set_margin_start(GTK_WIDGET(entries_operation_virement), 10);
    gtk_widget_set_margin_end(GTK_WIDGET(entries_operation_virement), 10);
    gtk_widget_set_halign(GTK_WIDGET(entries_operation_virement), GTK_ALIGN_CENTER);
    gtk_widget_set_valign(GTK_WIDGET(entries_operation_virement), GTK_ALIGN_CENTER);
    GtkWidget *Id_virement_entry = gtk_entry_new();
    gtk_entry_set_placeholder_text(GTK_ENTRY(Id_virement_entry),"Enter account ID");
    gtk_box_append(GTK_BOX(entries_operation_virement), Id_virement_entry);
    GtkWidget *Id_virement_client_entry = gtk_entry_new();
    gtk_entry_set_placeholder_text(GTK_ENTRY(Id_virement_client_entry),"Enter client ID");
    gtk_box_append(GTK_BOX(entries_operation_virement), Id_virement_client_entry);
    GtkWidget *Id_virement_TO = gtk_entry_new();
    gtk_entry_set_placeholder_text(GTK_ENTRY(Id_virement_TO),"Enter account ID (receiver)");
    gtk_box_append(GTK_BOX(entries_operation_virement), Id_virement_TO);
    GtkWidget *Id_virement_client_TO = gtk_entry_new();
    gtk_entry_set_placeholder_text(GTK_ENTRY(Id_virement_client_TO),"Enter client ID (receiver)");
    gtk_box_append(GTK_BOX(entries_operation_virement), Id_virement_client_TO);
    GtkWidget *MONTANT_VERSE = gtk_entry_new();
    gtk_entry_set_placeholder_text(GTK_ENTRY(MONTANT_VERSE),"Enter amount to transfer");
    gtk_box_append(GTK_BOX(entries_operation_virement), MONTANT_VERSE);
    GtkWidget *info_virement_label = gtk_label_new("");
    gtk_box_append(GTK_BOX(entries_operation_virement), info_virement_label);
    gtk_box_append(GTK_BOX(POPUP_OPERATION_VIREMENT), entries_operation_virement);
    gtk_widget_set_size_request(Id_virement_entry, 500, -1);
    GtkWidget *button_box_virement = gtk_box_new(GTK_ORIENTATION_HORIZONTAL, 450);
    gtk_widget_set_hexpand(button_box_virement, TRUE);
    GtkWidget *OK_BUTTON_VIREMENT = gtk_button_new_with_label("OK");
    GtkWidget *CANCEL_BUTTON_VIREMENT = gtk_button_new_with_label("Cancel");
    gtk_box_append(GTK_BOX(button_box_virement), OK_BUTTON_VIREMENT);
    gtk_box_append(GTK_BOX(button_box_virement), CANCEL_BUTTON_VIREMENT);
    gtk_box_append(GTK_BOX(entries_operation_virement), button_box_virement);
    gtk_widget_set_halign(OK_BUTTON_VIREMENT, GTK_ALIGN_START);
    gtk_widget_set_halign(CANCEL_BUTTON_VIREMENT, GTK_ALIGN_END);

    //----------------CONSULTATION-----------------------//
    GtkWidget *consultation_menu = gtk_box_new(GTK_ORIENTATION_VERTICAL, 0);
    gtk_widget_set_halign(consultation_menu, GTK_ALIGN_CENTER);
    gtk_widget_set_valign(consultation_menu, GTK_ALIGN_CENTER);
    gtk_widget_set_hexpand(consultation_menu, TRUE);
    gtk_widget_set_vexpand(consultation_menu, TRUE);
    // Title
    GtkWidget *consultation_label = gtk_label_new("Consultation");
    gtk_box_append(GTK_BOX(consultation_menu), consultation_label);
    gtk_widget_set_halign(consultation_label, GTK_ALIGN_CENTER);
    gtk_widget_set_valign(consultation_label, GTK_ALIGN_START);
    gtk_widget_set_margin_bottom(consultation_label, 20);
    GtkWidget *consultation_label_2 = gtk_label_new("None");
    gtk_box_append(GTK_BOX(consultation_menu), consultation_label_2);
    gtk_widget_set_halign(consultation_label_2, GTK_ALIGN_CENTER);
    gtk_widget_set_valign(consultation_label_2, GTK_ALIGN_CENTER);
    gtk_widget_set_visible(consultation_label_2, FALSE);
    // List view
    GtkWidget *consultation_list_view = create_consultation_list_view();
    gtk_box_append(GTK_BOX(consultation_menu), consultation_list_view);
    gtk_widget_set_hexpand(consultation_list_view, TRUE);
    gtk_widget_set_vexpand(consultation_list_view, TRUE);
    gtk_widget_set_visible(consultation_list_view, FALSE);
    // Entries box
    GtkWidget *C_ENTRIES_BOX = gtk_box_new(GTK_ORIENTATION_VERTICAL, 0);
    GtkWidget *Id_client_consultation = gtk_entry_new();
    gtk_entry_set_placeholder_text(GTK_ENTRY(Id_client_consultation),"Enter client ID");
    gtk_box_append(GTK_BOX(C_ENTRIES_BOX), Id_client_consultation);
    GtkWidget *Id_compte_consultation = gtk_entry_new();
    gtk_entry_set_placeholder_text(GTK_ENTRY(Id_compte_consultation),"Enter account ID");
    gtk_box_append(GTK_BOX(C_ENTRIES_BOX), Id_compte_consultation);
    GtkWidget *button_box_consultation = gtk_box_new(GTK_ORIENTATION_HORIZONTAL, 0);
    gtk_widget_set_hexpand(button_box_consultation, TRUE);
    GtkWidget *OK_BUTTON_CONSULTATION = gtk_button_new_with_label("OK");
    GtkWidget *CANCEL_BUTTON_CONSULTATION = gtk_button_new_with_label("Cancel");
    gtk_box_append(GTK_BOX(button_box_consultation), OK_BUTTON_CONSULTATION);
    gtk_box_append(GTK_BOX(button_box_consultation), CANCEL_BUTTON_CONSULTATION);
    gtk_box_append(GTK_BOX(C_ENTRIES_BOX), button_box_consultation);
    gtk_widget_set_halign(OK_BUTTON_CONSULTATION, GTK_ALIGN_START);
    gtk_widget_set_halign(CANCEL_BUTTON_CONSULTATION, GTK_ALIGN_END);
    GtkWidget *Info_consultation_label = gtk_label_new("");
    gtk_box_append(GTK_BOX(C_ENTRIES_BOX), Info_consultation_label);
    gtk_box_append(GTK_BOX(consultation_menu), C_ENTRIES_BOX);
    // Bottom cancel button
    GtkWidget *bottom_cancel_consultation = gtk_button_new_with_label("Cancel");
    gtk_box_append(GTK_BOX(consultation_menu), bottom_cancel_consultation);
    gtk_widget_set_halign(bottom_cancel_consultation, GTK_ALIGN_END);
    gtk_widget_set_visible(bottom_cancel_consultation, FALSE);

    gtk_stack_add_titled(GTK_STACK(stack), consultation_menu, "consultation_menu", "Consultation");
    GLOBAL_VISIBILTY_CONSULTATION_ACUN = consultation_label_2;
    GLOBAL_VISIBILTY_CONSULTATION = consultation_menu;
    GLOBAL_CONSULTATION_ENTRIES = C_ENTRIES_BOX;




    // global data //
    ClientData *client_data = g_malloc(sizeof(ClientData));
    client_data->window = window;
    client_data->id_entry = Id_entry;
    client_data->info_label = info_label;
    client_data->tel_entry = NUMERO_TELEPHONE;
    client_data->nom_entry = NOM_CLIENT;
    client_data->prenom_entry = PRENOM_CLIENT;
    client_data->profession_entry = PROFESSION_CLIENT;
    client_data->M_id_entry = Id_entry_2;
    client_data->M_info_label = info_label_2;
    client_data->M_tel_entry = NUMERO_TELEPHONE_2;
    client_data->M_nom_entry = NOM_CLIENT_2;
    client_data->M_prenom_entry = PRENOM_CLIENT_2;
    client_data->M_profession_entry = PROFESSION_CLIENT_2;
    client_data->D_id_entry = Id_entry_3;
    client_data->D_info_label = info_label_3;
    client_data->search_client_list = search_client_list_view;
    client_data->search_client_id_entry = Id_search_client;
    client_data->search_client_info_label = info_label_search;
    client_data->search_client_nom_entry = Nom_search_client;
    client_data->search_client_prenom_entry = Prenom_search_client;
    client_data->search_client_id_container = entries_container_search_id;
    client_data->search_client_name_container = entries_container_search_name;
    client_data->search_client_id_buttons = button_box_search_id;
    client_data->search_client_name_buttons = button_box_search_name;
    client_data->id_compte_entry = Id_compte_entry;
    client_data->info_label_compte = info_Compte_label;
    client_data->id_client_entry = Id_client_entry;
    client_data->nom_entry_compte = Nom_Compte_entry;
    client_data->prenom_entry_compte = Prenom_Compte_entry;
    client_data->solde_entry = Solde_Compte_entry;
    client_data->date_entry = Date_Compte_entry;
    client_data->fermeture_id_compte_entry = Id_fermeture_entry;
    client_data->fermeture_id_client_entry = Id_fermeture_client_entry;
    client_data->info_label_fermeture = info_label_fermeture;
    client_data->info_label_retrait = info_Withdrawal_label;
    client_data->id_client_retrait = Id_client_entry_retrait;
    client_data->id_compte_retrait = Id_compte_entry_retrait;
    client_data->retrait_entry = Withdrawal_entry;
    client_data->id_client_virement = Id_virement_client_entry;
    client_data->id_compte_virement = Id_virement_entry;
    client_data->id_virement_compte_TO = Id_virement_TO;
    client_data->id_virement_client_TO = Id_virement_client_TO;
    client_data->virement_entry = MONTANT_VERSE;
    client_data->info_label_virement = info_virement_label;
    client_data->consultation_list = consultation_list_view;
    client_data->OK_BUTTON_CONSULTATION = OK_BUTTON_CONSULTATION;
    client_data->CANCEL_BUTTON_CONSULTATION = CANCEL_BUTTON_CONSULTATION;
    client_data->id_client_consultation = Id_client_consultation;
    client_data->id_compte_consultation = Id_compte_consultation;
    client_data->Info_label_consultation = Info_consultation_label;
    client_data->bottom_cancel_consultation = bottom_cancel_consultation;
    client_data->confirm_add_client = 0;
    client_data->confirm_edit_client = 0;
    client_data->confirm_delete_client = 0;
    client_data->confirm_add_compte = 0;
    client_data->confirm_fermeture_compte = 0;
    client_data->confirm_retrait = 0;
    client_data->confirm_virement = 0;
    client_data->confirm_consultation = 0;
    client_data->confirm_search_client = 0;

   
    // adding data to buttons
    g_object_set_data(G_OBJECT(btn_clients), "page", "clients");
    g_object_set_data(G_OBJECT(btn_comptes), "page", "Compte_Menu");
    g_object_set_data(G_OBJECT(btn_ops), "page", "Operation_Menu");
    g_object_set_data(G_OBJECT(btn_back), "page", "main");
    g_object_set_data(G_OBJECT(btn_add), "Setvisibility", "add");
    g_object_set_data(G_OBJECT(btn_edit), "Setvisibility", "edit");
    g_object_set_data(G_OBJECT(btn_back_compte), "page", "main");
    g_object_set_data(G_OBJECT(btn_back_compte), "Setvisibility", "cancel_compte");
    g_object_set_data(G_OBJECT(CANCEL_BUTTON), "Setvisibility", "cancel");
    g_object_set_data(G_OBJECT(CANCEL_BUTTON_2), "Setvisibility", "cancel");
    g_object_set_data(G_OBJECT(btn_back), "Setvisibility", "main");
    g_object_set_data(G_OBJECT(btn_delete), "Setvisibility", "delete");
    g_object_set_data(G_OBJECT(btn_search), "Setvisibility", "search_client_choice");
    g_object_set_data(G_OBJECT(btn_search_choice_cancel), "Setvisibility", "cancel");
    g_object_set_data(G_OBJECT(CANCEL_BUTTON_3), "Setvisibility", "cancel");
    g_object_set_data(G_OBJECT(btn_fermeture_compte), "Setvisibility", "fermeture_compte");
    g_object_set_data(G_OBJECT(CANCEL_BUTTON_FERMETURE), "Setvisibility", "cancel_fermeture");
    g_object_set_data(G_OBJECT(btn_nouveau_compte), "Setvisibility", "nouveau_compte");
    g_object_set_data(G_OBJECT(CANCEL_BUTTON_COMPTE), "Setvisibility", "cancel_compte");
    g_object_set_data(G_OBJECT(CANCEL_BUTTON_VIREMENT), "Setvisibility", "cancel_virement");
    g_object_set_data(G_OBJECT(CANCEL_BUTTON_OPERATION_RETRAIT), "Setvisibility", "cancel_retrait");
    g_object_set_data(G_OBJECT(btn_back_operation), "page", "main");
    g_object_set_data(G_OBJECT(btn_back_operation), "Setvisibility", "cancel_operation");
    g_object_set_data(G_OBJECT(btn_virement), "Setvisibility", "operation_virement");
    g_object_set_data(G_OBJECT(btn_retrait), "Setvisibility", "operation_retrait");
    g_object_set_data(G_OBJECT(btn_consultation), "page", "consultation_menu");
    g_object_set_data(G_OBJECT(btn_consultation), "Setvisibility", "consultation");
    g_object_set_data(G_OBJECT(CANCEL_BUTTON_CONSULTATION), "page", "Compte_Menu");
    g_object_set_data(G_OBJECT(CANCEL_BUTTON_CONSULTATION), "Setvisibility", "cancel");


    
    // button signals
    g_signal_connect_swapped(btn_quit, "clicked", G_CALLBACK(gtk_window_close), window);
    g_signal_connect(btn_clients, "clicked", G_CALLBACK(switch_page), stack);
    g_signal_connect(btn_comptes, "clicked", G_CALLBACK(switch_page), stack);
    g_signal_connect(btn_ops, "clicked", G_CALLBACK(switch_page), stack);
    g_signal_connect(btn_back, "clicked", G_CALLBACK(switch_page), stack);
    g_signal_connect(btn_consultation, "clicked", G_CALLBACK(switch_page), stack);
    g_signal_connect(btn_add, "clicked", G_CALLBACK(POP_UP_VISIBILITY), NULL);
    g_signal_connect(CANCEL_BUTTON, "clicked", G_CALLBACK(POP_UP_VISIBILITY), NULL);
    g_signal_connect(CANCEL_BUTTON, "clicked", G_CALLBACK(on_cancel_add_client_confirm), client_data);
    g_signal_connect(btn_back, "clicked", G_CALLBACK(POP_UP_VISIBILITY), NULL);
    g_signal_connect(btn_back_compte, "clicked", G_CALLBACK(POP_UP_VISIBILITY), NULL);
    g_signal_connect(btn_back_compte, "clicked", G_CALLBACK(switch_page), stack);
    g_signal_connect(btn_edit, "clicked", G_CALLBACK(POP_UP_VISIBILITY), NULL);
    g_signal_connect(CANCEL_BUTTON_2, "clicked", G_CALLBACK(POP_UP_VISIBILITY), NULL);
    g_signal_connect(CANCEL_BUTTON_2, "clicked", G_CALLBACK(on_cancel_edit_client_confirm), client_data);
    g_signal_connect(btn_delete, "clicked", G_CALLBACK(POP_UP_VISIBILITY), NULL);
    g_signal_connect(CANCEL_BUTTON_3, "clicked", G_CALLBACK(POP_UP_VISIBILITY), NULL);
    g_signal_connect(CANCEL_BUTTON_3, "clicked", G_CALLBACK(on_cancel_delete_client_confirm), client_data);
    g_signal_connect(btn_search, "clicked", G_CALLBACK(POP_UP_VISIBILITY), NULL);
    g_signal_connect(btn_search_by_id, "clicked", G_CALLBACK(on_open_search_client_by_id), client_data);
    g_signal_connect(btn_search_by_name, "clicked", G_CALLBACK(on_open_search_client_by_name), client_data);
    g_signal_connect(btn_search_choice_cancel, "clicked", G_CALLBACK(POP_UP_VISIBILITY), NULL);
    g_signal_connect(OK_BUTTON_SEARCH_ID, "clicked", G_CALLBACK(on_ok_search_client), client_data);
    g_signal_connect(CANCEL_BUTTON_SEARCH_ID, "clicked", G_CALLBACK(POP_UP_VISIBILITY), NULL);
    g_signal_connect(CANCEL_BUTTON_SEARCH_ID, "clicked", G_CALLBACK(on_cancel_search_client), client_data);
    g_signal_connect(OK_BUTTON_SEARCH_NAME, "clicked", G_CALLBACK(on_ok_search_client_by_name), client_data);
    g_signal_connect(CANCEL_BUTTON_SEARCH_NAME, "clicked", G_CALLBACK(POP_UP_VISIBILITY), NULL);
    g_signal_connect(CANCEL_BUTTON_SEARCH_NAME, "clicked", G_CALLBACK(on_cancel_search_client), client_data);
    g_signal_connect(btn_consultation, "clicked", G_CALLBACK(POP_UP_VISIBILITY), "consultation");
    g_signal_connect(CANCEL_BUTTON_CONSULTATION, "clicked", G_CALLBACK(POP_UP_VISIBILITY), NULL);
    g_signal_connect(CANCEL_BUTTON_CONSULTATION, "clicked", G_CALLBACK(switch_page), stack);
    g_signal_connect(CANCEL_BUTTON_CONSULTATION, "clicked", G_CALLBACK(on_cancel_consultation), client_data);
    g_signal_connect(btn_fermeture_compte, "clicked", G_CALLBACK(POP_UP_VISIBILITY), NULL);
    g_signal_connect(CANCEL_BUTTON_FERMETURE, "clicked", G_CALLBACK(POP_UP_VISIBILITY), NULL);
    g_signal_connect(CANCEL_BUTTON_FERMETURE, "clicked", G_CALLBACK(on_cancel_fermeture_compte_confirm), client_data);
    g_signal_connect(btn_nouveau_compte, "clicked", G_CALLBACK(POP_UP_VISIBILITY), NULL);
    g_signal_connect(CANCEL_BUTTON_COMPTE, "clicked", G_CALLBACK(POP_UP_VISIBILITY), NULL);
    g_signal_connect(CANCEL_BUTTON_COMPTE, "clicked", G_CALLBACK(on_cancel_add_compte_confirm), client_data);
    g_signal_connect(CANCEL_BUTTON_VIREMENT, "clicked", G_CALLBACK(POP_UP_VISIBILITY), NULL);
    g_signal_connect(CANCEL_BUTTON_VIREMENT, "clicked", G_CALLBACK(on_cancel_virement_confirm), client_data);
    g_signal_connect(OK_BUTTON_VIREMENT, "clicked", G_CALLBACK(on_ok_virement_compte), client_data);
    g_signal_connect(bottom_cancel_consultation, "clicked", G_CALLBACK(on_bottom_cancel_consultation), client_data);
    g_signal_connect(OK_BUTTON_CONSULTATION, "clicked", G_CALLBACK(on_ok_consultation), client_data);
    g_signal_connect(CANCEL_BUTTON_OPERATION_RETRAIT, "clicked", G_CALLBACK(POP_UP_VISIBILITY), NULL);
    g_signal_connect(CANCEL_BUTTON_OPERATION_RETRAIT, "clicked", G_CALLBACK(on_cancel_retrait_confirm), client_data);
    g_signal_connect(OK_BUTTON_OPERATION_RETRAIT, "clicked", G_CALLBACK(on_ok_retrait_compte), client_data);
    g_signal_connect(btn_retrait, "clicked", G_CALLBACK(POP_UP_VISIBILITY), NULL);
    g_signal_connect(btn_virement, "clicked", G_CALLBACK(POP_UP_VISIBILITY), NULL);
    g_signal_connect(btn_back_operation, "clicked", G_CALLBACK(switch_page), stack);
    g_signal_connect(btn_back_operation, "clicked", G_CALLBACK(POP_UP_VISIBILITY), NULL);
    g_signal_connect(OK_BUTTON, "clicked", G_CALLBACK(on_ok_add_client), client_data);
    g_signal_connect(OK_BUTTON_2, "clicked", G_CALLBACK(on_ok_edit_client), client_data);
    g_signal_connect(OK_BUTTON_3, "clicked", G_CALLBACK(on_ok_delete_client), client_data);
    g_signal_connect(OK_BUTTON_COMPTE, "clicked", G_CALLBACK(on_ok_add_compte), client_data);
    g_signal_connect(OK_BUTTON_FERMETURE, "clicked", G_CALLBACK(on_fermeture_compte_button), client_data);
    
  
    //current window
    gtk_window_present(GTK_WINDOW(window));

}

int main(int argc, char **argv) {
    gtk_widget_set_default_direction(GTK_TEXT_DIR_LTR);
    GtkApplication *app = gtk_application_new("com.example.gestion", G_APPLICATION_DEFAULT_FLAGS);
    g_signal_connect(app, "activate", G_CALLBACK(on_activate), NULL);
    int status = g_application_run(G_APPLICATION(app), argc, argv);
    g_object_unref(app);
    return status;
}


